version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile.app
    volumes:
      - static_volume:/home/app/public
    command: node server.js
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/public
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume: